apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - grafana.yaml
  - grafana-datasources.yaml
  - grafana-dashboard-configmap.yaml
  - loki.yaml
  - prometheus.yaml
  - promtail.yaml
  - servicemonitors.yaml
